---
version: '3'
vars:
  workdir: .work
  mirror: https://dl-cdn.alpinelinux.org/alpine
  major_ver: 3
  minor_ver: 17
  patch_ver: 1
  arch: x86_64
  fq_ver: '{{ .major_ver }}.{{ .minor_ver }}.{{ .patch_ver }}'
  prefix: alpine-standard-{{ .fq_ver }}-{{ .arch }}
  iso: '{{ .prefix }}.iso'
  url: '{{ .mirror }}/v{{ .major_ver }}.{{ .minor_ver }}/releases/{{ .arch }}/{{ .iso }}'
  fq_iso: '{{ .workdir }}/{{ .iso }}'
  data_disk_fmt: qcow2
  fq_data_disk: '{{ .workdir }}/{{ .prefix }}-data.{{ .data_disk_fmt }}'
tasks:
  dl-iso:
    cmds:
      - curl -sSLf -o {{ .fq_iso | quote }} {{ .url | quote }}
    status:
      - test -f {{ .fq_url | quote }}
  create-data-disk:
    vars:
      s: '8G'
    cmds:
      - qemu-img create -f "{{ .data_disk_fmt }}" {{ .fq_data_disk | quote }} {{ .s | quote }}
    status:
      - test -f {{ .fq_data_disk | quote }}
  delete-data-disk:
    cmds:
      - powershell Remove-Item -Force {{ .fq_data_disk | quote }}
  launch-vm:
    vars:
      m: '{{ .m | default 512 }}'
      nic: '{{ .nic | default "user" }}'
      boot: '{{ .boot | default "d" }}'
      cdrom: '{{ .cdrom | default .fq_iso }}'
    deps:
      - dl-iso
      - create-data-disk
    cmds:
      - |
        qemu-system-{{ .arch }} \
          -m {{ .m }} \
          {{ if .nic }}-nic {{ .nic | quote }}{{ end }} \
          {{ if .boot }}-boot {{ .boot | quote }}{{ end }} \
          {{ if .cdrom }}-cdrom {{ .cdrom | quote }}{{ end }} \
          {{ if .display }}-display {{ .display }}{{ end }} \
          {{ if .enable_kvm }}-enable-kvm{{ end }} \
          -drive if=none,id=stick,format={{ .data_disk_fmt }},file={{ .fq_data_disk }} \
          -device nec-usb-xhci,id=xhci \
          -device usb-storage,bus=xhci.0,drive=stick
